""" OTp Email

Revision ID: 038a03466b48
Revises: 9fbac7d0abd0
Create Date: 2024-10-29 16:52:44.322738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038a03466b48'
down_revision: Union[str, None] = '9fbac7d0abd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verification', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_otp_verification_email'), 'otp_verification', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verification_email'), table_name='otp_verification')
    op.drop_column('otp_verification', 'email')
    # ### end Alembic commands ###
