""" driver model update

Revision ID: 14562fa1459d
Revises: c94450fb918c
Create Date: 2024-11-14 20:47:40.688455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14562fa1459d'
down_revision: Union[str, None] = 'c94450fb918c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('vehicle_name', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_model', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_insurance_policy', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_exterior_color', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_interior_color', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('nin_photo', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('nin_number', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('proof_of_ownership', sa.String(), nullable=True))
    op.alter_column('drivers', 'license_expiry',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('drivers', 'years_of_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'drivers', ['vehicle_interior_color'])
    op.create_unique_constraint(None, 'drivers', ['nin_photo'])
    op.create_unique_constraint(None, 'drivers', ['nin_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.alter_column('drivers', 'years_of_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('drivers', 'license_expiry',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('drivers', 'proof_of_ownership')
    op.drop_column('drivers', 'nin_number')
    op.drop_column('drivers', 'nin_photo')
    op.drop_column('drivers', 'vehicle_interior_color')
    op.drop_column('drivers', 'vehicle_exterior_color')
    op.drop_column('drivers', 'vehicle_insurance_policy')
    op.drop_column('drivers', 'vehicle_model')
    op.drop_column('drivers', 'vehicle_name')
    # ### end Alembic commands ###
