"""referral code updatee

Revision ID: 2a969e4a7d8a
Revises: 4caf9c3c7e29
Create Date: 2024-12-27 11:06:04.252697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a969e4a7d8a'
down_revision: Union[str, None] = '4caf9c3c7e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'social_security_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('social_security_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
