"""panic button

Revision ID: 2bda3ddebfaa
Revises: 5c9fcdc7688a
Create Date: 2025-01-05 07:50:28.600636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bda3ddebfaa'
down_revision: Union[str, None] = '5c9fcdc7688a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panic_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panic_buttons_id'), 'panic_buttons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_panic_buttons_id'), table_name='panic_buttons')
    op.drop_table('panic_buttons')
    # ### end Alembic commands ###
