""" cordinates updated rides

Revision ID: 46978598ae09
Revises: f9d1327d4ce5
Create Date: 2025-01-25 13:41:30.283326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46978598ae09'
down_revision: Union[str, None] = 'f9d1327d4ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('drivers', 'pickup_longitude')
    op.drop_column('drivers', 'pickup_latitude')
    op.add_column('rides', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.drop_column('rides', 'longitude')
    op.drop_column('rides', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rides', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('rides', 'pickup_longitude')
    op.drop_column('rides', 'pickup_latitude')
    op.add_column('drivers', sa.Column('pickup_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('pickup_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('drivers', 'longitude')
    op.drop_column('drivers', 'latitude')
    # ### end Alembic commands ###
