""" usa drivers

Revision ID: 4aef9c91cf42
Revises: 6393826833c3
Create Date: 2024-12-23 21:27:23.874709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aef9c91cf42'
down_revision: Union[str, None] = '6393826833c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('ssn_number', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('ssn_photo', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_inspection_approval', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'drivers', ['ssn_number'])
    op.add_column('riders', sa.Column('social_security_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'social_security_number')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'vehicle_inspection_approval')
    op.drop_column('drivers', 'ssn_photo')
    op.drop_column('drivers', 'ssn_number')
    # ### end Alembic commands ###
