"""temporal photo updated

Revision ID: 5c9fcdc7688a
Revises: 8bacd932c2b3
Create Date: 2025-01-04 18:33:25.280573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9fcdc7688a'
down_revision: Union[str, None] = '8bacd932c2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temporary_user_photos', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('temporary_user_photos', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temporary_user_photos', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('temporary_user_photos', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
