""" Driver model modification

Revision ID: 6393826833c3
Revises: 891f4d7edd58
Create Date: 2024-11-19 05:11:08.515320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6393826833c3'
down_revision: Union[str, None] = '891f4d7edd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drivers_vehicle_interior_color_key', 'drivers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('drivers_vehicle_interior_color_key', 'drivers', ['vehicle_interior_color'])
    # ### end Alembic commands ###
