"""pass reset table reset token table added

Revision ID: 65d139cd141e
Revises: c0e53503b7cf
Create Date: 2024-12-26 10:09:53.617750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d139cd141e'
down_revision: Union[str, None] = 'c0e53503b7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('reset_token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'password_resets', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_resets', type_='unique')
    op.drop_column('password_resets', 'reset_token')
    # ### end Alembic commands ###
