""" driver model update 3

Revision ID: 8648e5a855f9
Revises: 14562fa1459d
Create Date: 2024-11-15 13:02:46.030221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8648e5a855f9'
down_revision: Union[str, None] = '14562fa1459d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'driver_photo',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('drivers_nin_photo_key', 'drivers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('drivers_nin_photo_key', 'drivers', ['nin_photo'])
    op.alter_column('drivers', 'driver_photo',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
