"""Add REFERRAL_BONUS to WalletTransactionEnum

Revision ID: 8ff360f07e3f
Revises: 637f37be9fb3
Create Date: 2024-10-16 08:11:28.796719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff360f07e3f'
down_revision: Union[str, None] = '637f37be9fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add REFERRAL_BONUS to the wallet_transaction_enum enum
    op.execute("ALTER TYPE wallet_transaction_enum ADD VALUE 'REFERRAL_BONUS';")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
