"""Chatmessanger update

Revision ID: 9ec3d00cb98d
Revises: 75b84ad0b19f
Create Date: 2024-10-20 15:38:40.621115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec3d00cb98d'
down_revision: Union[str, None] = '75b84ad0b19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
