""" Company wallet account number update

Revision ID: 9fbac7d0abd0
Revises: 736b8c08c5ae
Create Date: 2024-10-28 06:28:34.256794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbac7d0abd0'
down_revision: Union[str, None] = '736b8c08c5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_wallet', sa.Column('account_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'company_wallet', ['account_number'])
    op.add_column('transactions', sa.Column('company_wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'company_wallet', ['company_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'company_wallet_id')
    op.drop_constraint(None, 'company_wallet', type_='unique')
    op.drop_column('company_wallet', 'account_number')
    # ### end Alembic commands ###
