""" cordinates

Revision ID: c01de67b8540
Revises: 493d296c4936
Create Date: 2025-01-24 20:51:53.027126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01de67b8540'
down_revision: Union[str, None] = '493d296c4936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_locations',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_driver_locations_driver_id'), 'driver_locations', ['driver_id'], unique=False)
    op.add_column('drivers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('panic_activated', sa.Boolean(), nullable=True))
    op.add_column('rides', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'longitude')
    op.drop_column('rides', 'latitude')
    op.drop_column('rides', 'panic_activated')
    op.drop_column('drivers', 'longitude')
    op.drop_column('drivers', 'latitude')
    op.drop_index(op.f('ix_driver_locations_driver_id'), table_name='driver_locations')
    op.drop_table('driver_locations')
    # ### end Alembic commands ###
