"""pass reset table pudated

Revision ID: c0e53503b7cf
Revises: f838da991aa8
Create Date: 2024-12-25 09:54:53.345024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e53503b7cf'
down_revision: Union[str, None] = 'f838da991aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('otp_code', sa.String(length=6), nullable=False))
    op.drop_constraint('password_resets_reset_token_key', 'password_resets', type_='unique')
    op.drop_column('password_resets', 'reset_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('password_resets_reset_token_key', 'password_resets', ['reset_token'])
    op.drop_column('password_resets', 'otp_code')
    # ### end Alembic commands ###
