""" cordinates update rides

Revision ID: c7d2bab40efd
Revises: c01de67b8540
Create Date: 2025-01-25 13:35:22.597811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d2bab40efd'
down_revision: Union[str, None] = 'c01de67b8540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('dropoff_latitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('dropoff_longitude', sa.Float(), nullable=True))
    op.drop_column('drivers', 'latitude')
    op.drop_column('drivers', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('drivers', 'dropoff_longitude')
    op.drop_column('drivers', 'dropoff_latitude')
    op.drop_column('drivers', 'pickup_longitude')
    op.drop_column('drivers', 'pickup_latitude')
    # ### end Alembic commands ###
