""" updated otp table

Revision ID: ca7779466a6b
Revises: 00574ee0e5d1
Create Date: 2024-11-02 17:14:29.213706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7779466a6b'
down_revision: Union[str, None] = '00574ee0e5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('otp_type', sa.Enum('EMAIL', 'SMS', name='otptypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'otp_type')
    # ### end Alembic commands ###
