""" Referal code Driver added

Revision ID: d3738cfdba4e
Revises: 9ec3d00cb98d
Create Date: 2024-10-25 14:43:21.796533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3738cfdba4e'
down_revision: Union[str, None] = '9ec3d00cb98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('referral_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'drivers', ['referral_code'])
    op.add_column('referrals', sa.Column('referrer_rider_id', sa.Integer(), nullable=True))
    op.add_column('referrals', sa.Column('referrer_driver_id', sa.Integer(), nullable=True))
    op.drop_constraint('referrals_referrer_id_fkey', 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'drivers', ['referrer_driver_id'], ['id'])
    op.create_foreign_key(None, 'referrals', 'riders', ['referrer_rider_id'], ['id'])
    op.drop_column('referrals', 'referrer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key('referrals_referrer_id_fkey', 'referrals', 'riders', ['referrer_id'], ['id'])
    op.drop_column('referrals', 'referrer_driver_id')
    op.drop_column('referrals', 'referrer_rider_id')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'referral_code')
    # ### end Alembic commands ###
