"""Add ssn_number to riders

Revision ID: dc571aaf5e38
Revises: 4aef9c91cf42
Create Date: 2024-12-24 07:29:18.926513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc571aaf5e38'
down_revision: Union[str, None] = '4aef9c91cf42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('ssn_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'riders', ['ssn_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'riders', type_='unique')
    op.drop_column('riders', 'ssn_number')
    # ### end Alembic commands ###
