""" updated otp table null

Revision ID: fd8c6dc8a750
Revises: ca7779466a6b
Create Date: 2024-11-02 19:41:18.410987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd8c6dc8a750'
down_revision: Union[str, None] = 'ca7779466a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'otp_type',
               existing_type=postgresql.ENUM('EMAIL', 'SMS', name='otptypeenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'otp_type',
               existing_type=postgresql.ENUM('EMAIL', 'SMS', name='otptypeenum'),
               nullable=False)
    # ### end Alembic commands ###
